create database ccondae;

use ccondae;

create table category (
    id BIGINT primary key,
    count int default 0,
    name varchar(255)
);

INSERT INTO category (id, name) VALUES
(1, 'React'),
(2, 'Vue.js'),
(3, 'Angular'),
(4, 'Spring Boot'),
(5, 'Django'),
(6, 'Flask'),
(7, 'Laravel'),
(8, 'Ruby on Rails'),
(9, 'Express'),
(10, 'ASP.NET'),
(11, 'Java'),
(12, 'Python'),
(13, 'JavaScript'),
(14, 'C#'),
(15, 'PHP'),
(16, 'Ruby'),
(17, 'C++'),
(18, 'C'),
(19, 'Swift'),
(20, 'Objective-C'),
(21, 'Kotlin'),
(22, 'Scala'),
(23, 'Go'),
(24, 'Rust'),
(25, 'TypeScript'),
(26, 'Elixir'),
(27, 'Haskell'),
(28, 'Clojure'),
(29, 'Erlang'),
(30, 'Perl'),
(31, 'Lua'),
(32, 'R'),
(33, 'Sass'),
(34, 'LESS'),
(35, 'GraphQL'),
(36, 'Webpack'),
(37, 'Babel'),
(38, 'Tailwind CSS'),
(39, 'Bootstrap'),
(40, 'Foundation'),
(41, 'Node.js'),
(42, 'Meteor'),
(43, 'Cordova'),
(44, 'Ionic'),
(45, 'TensorFlow'),
(46, 'PyTorch'),
(47, 'Keras'),
(48, 'Pandas'),
(49, 'NumPy'),
(50, 'Docker');
