# 버전 명시 안해주면 빌드 안됨
version: '3'
services:
  dev:
    build:
      context: ./dev/
      dockerfile: Dockerfile
    ports:
#      - "10022:22"
      - "8080:8080"
      - "80:80"
      - "443:443"

  # Docker 내부에서 접근할 때 : mysql://mysql:3306/your_database
  mysql:
    image: mysql:latest
    container_name: mysql
    # ports:
    #   - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /dev/sdb

  redis-test:
    image: redis:latest
    container_name: redis
#    ports:
#      - :6379
    volumes:
      - /dev/sdc